# Generated by Django 5.2.3 on 2025-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='port',
            field=models.PositiveIntegerField(default=8000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together={('ip_address', 'port')},
        ),
    ]
