# Generated by Django 5.2.3 on 2025-06-25 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_machine_port_alter_machine_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('cpu', 'CPU'), ('mem', 'Memory'), ('disk', 'Disk')], max_length=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.machine')),
            ],
            options={
                'unique_together': {('machine', 'incident_type', 'end_time')},
            },
        ),
    ]
